"""initial schema

Revision ID: 93b61132d6c4
Revises:
Create Date: 2026-10-05 17:36:42.613052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "93b61132d6c4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
        sa.Column("image", sa.JSON(), nullable=True),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("root_id", sa.Integer(), nullable=True),
        sa.Column("admin_commission_rate", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["root_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_id", "name", name="uq_category_name_per_parent"),
    )
    op.create_index(
        op.f("ix_categories_is_active"), "categories", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_categories_level"), "categories", ["level"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.create_index(
        op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_categories_root_id"), "categories", ["root_id"], unique=False
    )
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("contactinfo", sa.JSON(), nullable=True),
        sa.Column("image", sa.JSON(), nullable=True),
        sa.Column("is_root", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("use_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("currency_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("currency_symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("default_shop_id", sa.Integer(), nullable=True),
        sa.Column("token_version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_default_shop_id"), "users", ["default_shop_id"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_full_name"), "users", ["full_name"], unique=False)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=False)
    op.create_index(
        "uq_users_phone_verified",
        "users",
        ["phone"],
        unique=True,
        postgresql_where=sa.text("verified = true"),
    )
    op.create_index(
        "uq_users_verified_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email_verified = true"),
    )
    op.create_table(
        "shops",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cover_image", sa.JSON(), nullable=True),
        sa.Column("logo", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("address", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("owner_id"),
    )
    op.create_index(op.f("ix_shops_slug"), "shops", ["slug"], unique=True)
    # users <-> shops are circular: add this FK after both tables exist
    op.create_foreign_key(
        "fk_users_default_shop_id_shops",
        "users",
        "shops",
        ["default_shop_id"],
        ["id"],
    )
    op.create_table(
        "carts",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("shop_id", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "shop_id", "status", name="uq_cart_user_shop_status"
        ),
    )
    op.create_index(op.f("ix_carts_shop_id"), "carts", ["shop_id"], unique=False)
    op.create_index(op.f("ix_carts_status"), "carts", ["status"], unique=False)
    op.create_index(op.f("ix_carts_user_id"), "carts", ["user_id"], unique=False)
    op.create_table(
        "home_sections",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("full_width", sa.Boolean(), nullable=False),
        sa.Column("columns", sa.Integer(), nullable=True),
        sa.Column("autoplay", sa.Boolean(), nullable=False),
        sa.Column("product_limit", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_home_sections_category_id"),
        "home_sections",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_home_sections_is_active"), "home_sections", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_home_sections_position"), "home_sections", ["position"], unique=False
    )
    op.create_index(
        op.f("ix_home_sections_type"), "home_sections", ["type"], unique=False
    )
    op.create_table(
        "media",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("extension", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("original", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("media_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_mb", sa.Float(), nullable=True),
        sa.Column("thumbnail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("shop_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("CREATE SEQUENCE IF NOT EXISTS order_number_seq")
    op.create_table(
        "orders",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "order_number",
            sa.String(),
            server_default=sa.text("nextval('order_number_seq')::text"),
            nullable=False,
        ),
        sa.Column("subtotal", sa.Float(), nullable=False),
        sa.Column("discount", sa.Float(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("shipping_address", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_order_number"), "orders", ["order_number"], unique=True
    )
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column(
            "short_description",
            sqlmodel.sql.sqltypes.AutoString(length=800),
            nullable=True,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("whats_in_box", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumbnail", sa.JSON(), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column(
            "meta_title", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True
        ),
        sa.Column(
            "meta_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "video_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_category_id"), "products", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_shop_id"), "products", ["shop_id"], unique=False)
    op.create_index(op.f("ix_products_slug"), "products", ["slug"], unique=True)
    op.create_table(
        "roles",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "shop_id", name="uq_role_name_shop"),
    )
    op.create_index(op.f("ix_roles_shop_id"), "roles", ["shop_id"], unique=False)
    op.create_index(
        "uq_role_name_global",
        "roles",
        ["name"],
        unique=True,
        postgresql_where=sa.text("shop_id IS NULL"),
    )
    op.create_table(
        "shop_users",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "shop_id", name="uq_shop_user"),
    )
    op.create_index(
        op.f("ix_shop_users_shop_id"), "shop_users", ["shop_id"], unique=False
    )
    op.create_index(
        op.f("ix_shop_users_user_id"), "shop_users", ["user_id"], unique=False
    )
    op.create_table(
        "user_addresses",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.JSON(), nullable=True),
        sa.Column("location", sa.JSON(), nullable=True),
        sa.Column("default", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_addresses_default"), "user_addresses", ["default"], unique=False
    )
    op.create_index(
        op.f("ix_user_addresses_user_id"), "user_addresses", ["user_id"], unique=False
    )
    op.create_table(
        "banners",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("image", sa.JSON(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "background", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column(
            "link_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("open_in_new_tab", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["home_sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_banners_is_active"), "banners", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_banners_position"), "banners", ["position"], unique=False)
    op.create_index(
        op.f("ix_banners_section_id"), "banners", ["section_id"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("product_variant_id", sa.Integer(), nullable=True),
        sa.Column("product_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("actual_price", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("variant_attributes", sa.JSON(), nullable=True),
        sa.Column("image", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_items_shop_id"), "order_items", ["shop_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_items_status"), "order_items", ["status"], unique=False
    )
    op.create_table(
        "product_variants",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("sku", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("discount_price", sa.Float(), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("is_in_stock", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("image", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_variants_product_id"),
        "product_variants",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_sku"), "product_variants", ["sku"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_role"),
    )
    op.create_table(
        "cart_items",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("product_variant_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("variant_attributes", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cart_items_cart_id"), "cart_items", ["cart_id"], unique=False
    )
    op.create_index(
        op.f("ix_cart_items_product_id"), "cart_items", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_cart_items_product_variant_id"),
        "cart_items",
        ["product_variant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cart_items_product_variant_id"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_product_id"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_cart_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_product_variants_sku"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_product_id"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_order_items_status"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_shop_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_banners_section_id"), table_name="banners")
    op.drop_index(op.f("ix_banners_position"), table_name="banners")
    op.drop_index(op.f("ix_banners_is_active"), table_name="banners")
    op.drop_table("banners")
    op.drop_index(op.f("ix_user_addresses_user_id"), table_name="user_addresses")
    op.drop_index(op.f("ix_user_addresses_default"), table_name="user_addresses")
    op.drop_table("user_addresses")
    op.drop_index(op.f("ix_shop_users_user_id"), table_name="shop_users")
    op.drop_index(op.f("ix_shop_users_shop_id"), table_name="shop_users")
    op.drop_table("shop_users")
    op.drop_index(
        "uq_role_name_global",
        table_name="roles",
        postgresql_where=sa.text("shop_id IS NULL"),
    )
    op.drop_index(op.f("ix_roles_shop_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_products_slug"), table_name="products")
    op.drop_index(op.f("ix_products_shop_id"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_number"), table_name="orders")
    op.drop_table("orders")
    op.execute("DROP SEQUENCE IF EXISTS order_number_seq")
    op.drop_table("media")
    op.drop_index(op.f("ix_home_sections_type"), table_name="home_sections")
    op.drop_index(op.f("ix_home_sections_position"), table_name="home_sections")
    op.drop_index(op.f("ix_home_sections_is_active"), table_name="home_sections")
    op.drop_index(op.f("ix_home_sections_category_id"), table_name="home_sections")
    op.drop_table("home_sections")
    op.drop_index(op.f("ix_carts_user_id"), table_name="carts")
    op.drop_index(op.f("ix_carts_status"), table_name="carts")
    op.drop_index(op.f("ix_carts_shop_id"), table_name="carts")
    op.drop_table("carts")
    op.drop_constraint("fk_users_default_shop_id_shops", "users", type_="foreignkey")
    op.drop_index(op.f("ix_shops_slug"), table_name="shops")
    op.drop_table("shops")
    op.drop_index(
        "uq_users_verified_email",
        table_name="users",
        postgresql_where=sa.text("email_verified = true"),
    )
    op.drop_index(
        "uq_users_phone_verified",
        table_name="users",
        postgresql_where=sa.text("verified = true"),
    )
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_full_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_default_shop_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_root_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_level"), table_name="categories")
    op.drop_index(op.f("ix_categories_is_active"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
