from datetime import datetime, timedelta, timezone
from random import randint

from fastapi import APIRouter, Body, Depends, Response

from pydantic import EmailStr
from sqlmodel import or_, select

from sqlalchemy.orm import selectinload

from src.api.routers.auth.function import (
    generate_and_send_otp,
    issue_login_tokens,
    send_verification_email,
    verify_otp,
)
from src.api.core.smtp import send_email

from src.api.models.role_model.userRoleModel import UserRole
from src.api.core.response import api_response
from src.api.models.role_model.roleModel import Role
from src.api.core.security import (
    ALGORITHM,
    create_access_token,
    decode_token,
    exist_user,
    hash_password,
    verify_password,
    verify_refresh_token,
)
from src.api.core.dependencies import (
    GetSession,
    requireShopPermission,
    requireSignin,
    requireAdmin,
    requirePermission,
    requireShopAdmin,
)
from src.api.models.userModel import (
    EmailOtpRequest,
    EmailOtpVerifyRequest,
    LoginRequest,
    ResetPasswordWithOTPRequest,
    User,
    UserCreate,
    UserRead,
)

router = APIRouter(tags=["Auth"])


@router.post("/init", response_model=UserRead)
def initialize_first_user(request: UserCreate, session: GetSession):

    # Create first user with admin role
    hashed_password = hash_password(request.password)
    user = User(**request.model_dump())
    user.password = hashed_password
    user.is_root = True
    session.add(user)
    session.flush()
    # Prevent rerun if roles already exist
    existing_roles = session.exec(select(Role)).all()
    if existing_roles:
        return api_response(
            400,
            "Initialization already done",
        )

    # Create roles
    admin_role = Role(
        name="root",
        user_id=user.id,
        permissions=["all", "system:*"],
    )
    shop_admin_role = Role(
        name="Shop Admin",
        user_id=user.id,
        permissions=["shop:*"],
    )

    session.add(admin_role)
    session.add(shop_admin_role)
    session.flush()  # get IDs without committing

    # Assign admin role to the user via UserRole
    user_role_link = UserRole(user_id=user.id, role_id=admin_role.id)
    session.add(user_role_link)

    session.commit()
    session.refresh(user)

    user_read = UserRead.model_validate(user)

    return api_response(
        200,
        "Initialized admin user and roles",
        user_read,
    )


@router.post("/register", response_model=dict)
def register_user(
    request: UserCreate,
    session: GetSession,
):
    db_user = exist_user(session, email=request.email)
    if db_user:
        return api_response(
            400,
            "This user already exist",
        )
    user = User(**request.model_dump())  # Similar to new User(req.body) in Mongoose
    hashed_password = hash_password(user.password)
    user.password = hashed_password
    session.add(user)
    session.commit()
    session.refresh(user)  # Refresh to get updated fields (e.g., autogenerated ID)

    send_verification_email(user)

    user_read = UserRead.model_validate(user)  # ✅ Convert User → UserRead
    return api_response(
        200,
        "Check Your Email to Verify Your Account",
        user_read,
    )


@router.post("/login", response_model=UserRead)
def login_user(
    request: LoginRequest,
    response: Response,
    session: GetSession,
):

    # Detect email or phone
    identifier = request.identifier.strip()

    if "@" in identifier:
        user = session.exec(
            select(User)
            .options(selectinload(User.user_roles).selectinload(UserRole.role))
            .where(User.email == identifier)
        ).first()
    else:
        user = session.exec(
            select(User)
            .options(selectinload(User.user_roles).selectinload(UserRole.role))
            .where(or_(User.phone == identifier, User.unverified_phone == identifier))
        ).first()

    if not user:
        return api_response(400, "User not found")

    # If phone login → must be verified
    if not user.verified and "@" not in identifier:
        return api_response(401, "Please Login with Email, Your Number is Not Verified")

    # If email login → must be verified
    if "@" in identifier and not user.email_verified:
        return api_response(401, "Please verify your email before logging in")

    # OTP-only accounts (registered via /register-otp) have no password set
    if not user.password:
        return api_response(
            400, "This account has no password set. Please login via OTP instead."
        )
    if not verify_password(request.password, user.password):
        return api_response(401, "Incorrect password")
    if not user.is_active:
        return api_response(403, "User account is disabled")

    content = issue_login_tokens(user, response)
    return api_response(200, "Login successful", content)


# =====================================================================
# Passwordless auth — email + OTP only. No name/phone/country/etc required
# up front; those get collected later (e.g. at checkout via /user/update).
# =====================================================================


@router.post("/register-otp/send")
def register_otp_send(
    request: EmailOtpRequest,
    session: GetSession,
):
    email = request.email.strip().lower()
    user = session.exec(select(User).where(User.email == email)).first()

    if user and user.email_verified:
        return api_response(400, "This email is already registered. Please login.")

    if not user:
        # Minimal record — everything else (name, password, country, etc.)
        # is optional and gets filled in later.
        user = User(email=email)
        session.add(user)
        session.flush()

    generate_and_send_otp(
        session,
        user,
        purpose="register",
        subject="Your Registration Code",
        message="Your registration code is:",
    )

    return api_response(200, "Verification code sent. Please check your email.")


@router.post("/register-otp/verify", response_model=dict)
def register_otp_verify(
    request: EmailOtpVerifyRequest,
    response: Response,
    session: GetSession,
):
    email = request.email.strip().lower()
    user = session.exec(select(User).where(User.email == email)).first()
    if not user:
        return api_response(400, "Invalid email or code")

    if not verify_otp(user, request.otp.strip(), purpose="register"):
        return api_response(400, "Invalid or expired code")

    # OTP registration IS the verification step — no separate email-link
    # step, and no phone required to be considered a fully verified account.
    user.email_verified = True
    user.verified = True
    user.use_token = None
    session.add(user)
    session.commit()
    session.refresh(user)

    content = issue_login_tokens(user, response)
    return api_response(201, "Registration complete", content)


@router.post("/login-otp/send")
def login_otp_send(
    request: EmailOtpRequest,
    session: GetSession,
):
    email = request.email.strip().lower()
    user = session.exec(select(User).where(User.email == email)).first()

    if not user or not user.email_verified:
        return api_response(400, "No account found for this email. Please register.")
    if not user.is_active:
        return api_response(403, "User account is disabled")

    generate_and_send_otp(
        session,
        user,
        purpose="login",
        subject="Your Login Code",
        message="Your login code is:",
    )

    return api_response(200, "Verification code sent. Please check your email.")


@router.post("/login-otp/verify", response_model=dict)
def login_otp_verify(
    request: EmailOtpVerifyRequest,
    response: Response,
    session: GetSession,
):
    email = request.email.strip().lower()
    user = session.exec(select(User).where(User.email == email)).first()
    if not user:
        return api_response(400, "Invalid email or code")

    if not verify_otp(user, request.otp.strip(), purpose="login"):
        return api_response(400, "Invalid or expired code")

    if not user.is_active:
        return api_response(403, "User account is disabled")

    user.use_token = None
    session.add(user)
    session.commit()

    content = issue_login_tokens(user, response)
    return api_response(200, "Login successful", content)


@router.post("/resend-verification-email")
def resend_verification_email(
    session: GetSession,
    email: EmailStr = Body(...),
):
    email = email.strip().lower()
    user = session.exec(select(User).where(User.email == email)).first()

    if not user:
        return api_response(400, "User not found")
    if user.email_verified:
        return api_response(400, "This email is already verified. Please login.")

    send_verification_email(user)

    return api_response(200, "Verification email sent. Please check your inbox.")


@router.post(
    "/refresh",
)
def refresh_token(
    refresh_token: str,
):
    if not refresh_token:
        api_response(401, "Missing refresh token")

    payload = verify_refresh_token(refresh_token)
    if not payload:
        raise api_response(401, "Invalid refresh token")
    user = decode_token(refresh_token)
    # user = UserRead.model_validate(db_user)
    access_token = create_access_token(user)
    new_refresh_token = create_access_token(user_data=user, refresh=True)

    return api_response(
        200,
        "Refresh",
        {
            "access_token": access_token,
            "refresh_token": new_refresh_token,
            **user,
        },
    )


# forgot otp password send
@router.post("/otp-send-email")
def forgot_password(
    session: GetSession,
    email: EmailStr = Body(...),
):
    email = email.strip().lower()

    user = session.exec(select(User).where(User.email == email)).first()

    # ✅ Do NOT reveal whether email exists (security best practice)
    if not user:
        return api_response(200, "If this email exists, an OTP has been sent.")

    # Generate 6-digit OTP
    otp = f"{randint(100000, 999999)}"

    data = {"otp": otp, "email": email}
    otp_token = create_access_token(user_data=data, expires=timedelta(minutes=10))
    user.use_token = otp_token
    session.add(user)
    session.commit()

    # Send OTP via email or SMS
    send_email(
        to_email=user.email,
        subject="Your Password Reset OTP",
        body=f"Your OTP code is: {otp} (valid for 10 minutes)",
    )

    return api_response(200, "If this email exists, an OTP has been sent.")


@router.post("/reset-password")
def reset_password(
    request: ResetPasswordWithOTPRequest,
    session: GetSession,
):
    email = request.email.strip().lower()
    otp = request.otp.strip()
    new_password = request.new_password

    user = session.exec(select(User).where(User.email == email)).first()
    if not user:
        return api_response(400, "Invalid email or OTP")
    if not user.use_token:
        return api_response(400, "Expired OTP")
    decode = decode_token(user.use_token)
    if not decode:
        return api_response(400, "Invalid or expired OTP")

    data = decode.get("user", {})
    decoded_otp = data.get("otp")
    token_email = data.get("email")

    if decoded_otp != otp or token_email != email:
        return api_response(400, "Invalid OTP")

    # Reset password
    user.password = hash_password(new_password)
    user.use_token = None  # ✅ invalidate OTP
    user.updated_at = datetime.now(timezone.utc)

    session.add(user)
    session.commit()

    return api_response(200, "Password has been reset successfully")


@router.post("/logout")
def logout(response: Response):
    response.delete_cookie("refresh_token")
    response.delete_cookie("access_token")
    return {"message": "Logged out"}


@router.get("/testauth", response_model=dict)
def test_auth(
    user: requireSignin,
):
    return api_response(
        200,
        "Token is valid",
        {"user": user},
    )


@router.get("/testadmin")
def get_admin_data(
    user: requireAdmin,
):

    return {"message": f"Hello Admin {user['email']}", "user": user}


@router.get("/testpermission")
def get_admin_data(
    user=requirePermission("system:*"),
):
    return {"message": f"Hello Admin {user}"}


@router.get("/shop-admin")
def get_admin_data(
    user: requireShopAdmin,
):
    return api_response(
        200,
        f"Hello Shop Admin {user['email']}",
        {"user": user},
    )


@router.get("/shop-permissions")
def get_admin_data(
    user=requireShopPermission("product:create"),
):
    return api_response(
        200,
        f"Hello Shop Member {user['email']}, You have this shop permission",
        {"user": user},
    )
